server:
  port: 9090
  tomcat:
      max-threads: 200

spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.99.100:3306/suggestDB?useUnicode=true&characterEncoding=utf8
    username: root
    password: 0000
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      min-evictable-idle-time-millis: 3600000
      time-between-eviction-runs-millis: 60000
    hikari:
      maximum-pool-size: 1


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug


security:
  ignored: true
  basic:
    enabled: false


somun:
  properties:
    apiServer: http://localhost:8080
    searchIndexName: totalSearchIndex_v1.3
#    apiServer: https://api.gokgok.net

